In [1]:
# load csv files into dataframes 

import pandas as pd

# Loading Boston Globe dataset 
data1_b = pd.read_csv('/Users/rachelgupta/Desktop/NAACP - PIT NE/pitne-bias-in-media/summer24/Data/Combined_Datasets_3/2010/updated_bostonGlobe_2010.csv')

# census data, using 2010
data2_c = pd.read_csv('/Users/rachelgupta/Desktop/NAACP - PIT NE/pitne-bias-in-media/summer24/Data/Combined_Datasets_3/2010_N.csv')

#dropping rows with 'No TRACTSfound'
data1_b.dropna(subset=['Tracts'], inplace=True)
data1_b.head()

,Unnamed: 0,hl1_x,body,llama_prediction,Explicit_Pass_1,NER_Pass_1,NER_Pass_1_Sorted,NER_Pass_1_Coordinates,NER_prediction,NER_Sorted,...,author,lede,pub_date,indexing_terms,year,actual_body_word_count,body_cleaned,longitude,latitude,tract_2010
0,0,cerezyme alternative gets fda approval,washington the food and drug administration ha...,Here is my response based on the information...,NaN,"[(washington, 'GPE'), (less than one, 'CARDINA...","[(washington, 'GPE'), (the united states, 'GPE...",NaN,"[(1, 'CARDINAL'), (Boston, 'GPE'), (Massachuse...","[('Genzyme Corp.', 'ORG'), ('Genzyme Corp.', '...",...,Associated Press,washington - the food and drug administration ...,2010-02-27,"{'subject': [{'score': '91', 'classCode': 'ST0...",2010,91,washington food drug administration approved n...,-71.118563,42.362780,803
1,2,flawed calculus,in 1993 amy bishop and her husband james ander...,Based on the information provided in the art...,NaN,"[(1993, 'DATE'), (amy bishop, 'PERSON'), (jame...","[(children hospital, 'ORG'), (globe, 'ORG'), (...",NaN,"[(Boston, 'GPE'), (Massachusetts, 'GPE'), (Bos...","[('ATF', 'ORG'), ('Childrens Hospital', 'ORG')...",...,Kevin Cullen,"when it comes to amy bishop, the harvard-train...",2010-02-16,"{'subject': [{'score': '90', 'classCode': 'STX...",2010,555,"1993 , amy bishop husband , james anderson , q...",-71.058880,42.360082,30300
2,3,advantage kids,all these kids are at risk of being involved i...,Here is my assessment of the article's locat...,NaN,"[(williams, 'PERSON'), (tayleece, 'PERSON'), (...","[(the boston foundation, 'ORG'), (muriel s. sn...",NaN,"[(1, 'CARDINAL'), (Boston, 'GPE'), (South Bost...","[('the Sportsmen Club', 'FAC'), ('The Sportsme...",...,unknown,"in tennis, how you play can matter as much as ...",2010-07-20,"{'subject': [{'score': '90', 'classCode': 'STX...",2010,604,"kids risk involved gang- related activity , sa...",-71.058880,42.360082,30300
3,6,delahunt out field opens,democratic candidates include state senator ro...,Based on the information provided in the art...,NaN,"[(democratic, 'NORP'), (robert a. leary, 'PERS...","[(the state democratic party, 'ORG'), (the qui...",NaN,"[(the 10th Congressional District, 'LOC'), (Ma...","[('the 10th Congressional District', 'LOC'), (...",...,unknown,quincy - us representative william d. delahunt...,2010-03-06,"{'subject': [{'score': '91', 'classCode': 'ST0...",2010,811,democratic candidates include state senator ro...,-71.382437,42.407211,365100
4,7,wakefield boy dies after falling in pond,wakefield police responded about 11 30 a.m. to...,Based on the information provided in the art...,NaN,"[(wakefield, 'GPE'), (about 11 30 a.m., 'TIME'...","[(melrose wakefield hospital, 'ORG'), (wakefie...",NaN,"[(Wakefield, 'GPE'), (Massachusetts, 'GPE'), (...","[('Lake Street', 'FAC'), ('Lake Street', 'FAC'...",...,unknown,a 2-year-old boy drowned in a man-made pond in...,2010-04-27,"{'subject': [{'score': '90', 'classCode': 'STX...",2010,178,wakefield police responded 11 : 30 a. m. home ...,-71.163692,42.344704,402

In [2]:
# To examine full dataset without truncation 
pd.set_option('display.max_rows', None)  # None means display all rows
pd.set_option('display.max_columns', None)  # None means display all columns

In [3]:
#index names for boston globe data
data1_b.columns

Index(['Unnamed: 0', 'hl1_x', 'body', 'llama_prediction', 'Explicit_Pass_1',
       'NER_Pass_1', 'NER_Pass_1_Sorted', 'NER_Pass_1_Coordinates',
       'NER_prediction', 'NER_Sorted', 'NER_Sorted_Coordinates', 'Tracts',
       'position_section', 'position_subsection', 'hl1_y', 'hl2', 'author',
       'lede', 'pub_date', 'indexing_terms', 'year', 'actual_body_word_count',
       'body_cleaned', 'longitude', 'latitude', 'tract_2010'],
      dtype='object')

In [4]:
#index names for census data
data2_c.columns

Index(['geoid', 'cr_geoid', 'name', 'original_id', 'pop100', 'hu100',
       'state_place_fips'],
      dtype='object')

In [5]:
#processing boston globe data, the tracts are an array, making it into a list of strings
 
# cleaning function
def clean_tract(tract):
    return tract.strip("[]' ")

# Apply the function to the 'tract' column, replacing old column with this new info
data1_b['Tracts'] = data1_b['Tracts'].apply(clean_tract)

# Print the DataFrame to verify
#print(data1_b[['Tracts']].head())

data1_b.head()

,Unnamed: 0,hl1_x,body,llama_prediction,Explicit_Pass_1,NER_Pass_1,NER_Pass_1_Sorted,NER_Pass_1_Coordinates,NER_prediction,NER_Sorted,NER_Sorted_Coordinates,Tracts,position_section,position_subsection,hl1_y,hl2,author,lede,pub_date,indexing_terms,year,actual_body_word_count,body_cleaned,longitude,latitude,tract_2010
0,0,cerezyme alternative gets fda approval,washington the food and drug administration ha...,Here is my response based on the information...,NaN,"[(washington, 'GPE'), (less than one, 'CARDINA...","[(washington, 'GPE'), (the united states, 'GPE...",NaN,"[(1, 'CARDINAL'), (Boston, 'GPE'), (Massachuse...","[('Genzyme Corp.', 'ORG'), ('Genzyme Corp.', '...","[-71.1185629, 42.3627796]",000806,BUSINESS,unknown,cerezyme alternative gets fda approval,unknown,Associated Press,washington - the food and drug administration ...,2010-02-27,"{'subject': [{'score': '91', 'classCode': 'ST0...",2010,91,washington food drug administration approved n...,-71.118563,42.362780,803
1,2,flawed calculus,in 1993 amy bishop and her husband james ander...,Based on the information provided in the art...,NaN,"[(1993, 'DATE'), (amy bishop, 'PERSON'), (jame...","[(children hospital, 'ORG'), (globe, 'ORG'), (...",NaN,"[(Boston, 'GPE'), (Massachusetts, 'GPE'), (Bos...","[('ATF', 'ORG'), ('Childrens Hospital', 'ORG')...","[-71.0588801, 42.3600825]",030302,NEWS,Metro,flawed calculus,unknown,Kevin Cullen,"when it comes to amy bishop, the harvard-train...",2010-02-16,"{'subject': [{'score': '90', 'classCode': 'STX...",2010,555,"1993 , amy bishop husband , james anderson , q...",-71.058880,42.360082,30300
2,3,advantage kids,all these kids are at risk of being involved i...,Here is my assessment of the article's locat...,NaN,"[(williams, 'PERSON'), (tayleece, 'PERSON'), (...","[(the boston foundation, 'ORG'), (muriel s. sn...",NaN,"[(1, 'CARDINAL'), (Boston, 'GPE'), (South Bost...","[('the Sportsmen Club', 'FAC'), ('The Sportsme...","[-71.0588801, 42.3600825]",030302,NEWS,Metro,advantage kids,"with tennis, hub police get youths off city's ...",unknown,"in tennis, how you play can matter as much as ...",2010-07-20,"{'subject': [{'score': '90', 'classCode': 'STX...",2010,604,"kids risk involved gang- related activity , sa...",-71.058880,42.360082,30300
3,6,delahunt out field opens,democratic candidates include state senator ro...,Based on the information provided in the art...,NaN,"[(democratic, 'NORP'), (robert a. leary, 'PERS...","[(the state democratic party, 'ORG'), (the qui...",NaN,"[(the 10th Congressional District, 'LOC'), (Ma...","[('the 10th Congressional District', 'LOC'), (...","[-71.3824374, 42.4072107]",365100,NEWS,Metro,delahunt out field opens,republican candidates position themselves for ...,unknown,quincy - us representative william d. delahunt...,2010-03-06,"{'subject': [{'score': '91', 'classCode': 'ST0...",2010,811,democratic candidates include state senator ro...,-71.382437,42.407211,365100
4,7,wakefield boy dies after falling in pond,wakefield police responded about 11 30 a.m. to...,Based on the information provided in the art...,NaN,"[(wakefield, 'GPE'), (about 11 30 a.m., 'TIME'...","[(melrose wakefield hospital, 'ORG'), (wakefie...",NaN,"[(Wakefield, 'GPE'), (Massachusetts, 'GPE'), (...","[('Lake Street', 'FAC'), ('Lake Street', 'FAC'...","[-71.1636923, 42.3447035]",000402,NEWS,Metro,wakefield boy dies after falling in pond,wandered away as mother did chores,unknown,a 2-year-old boy drowned in a man-made pond in...,2010-04-27,"{'subject': [{'score': '90', 'classCode': 'STX...",2010,178,wakefield police responded 11 : 30 a. m. home ...,-71.163692,42.344704,402

In [7]:
#processing a subset of Census data, isolating location and geoid

d2_subset = data2_c[['geoid', 'name']]
d2_subset
d2_subset.dtypes   
# geoid is an int64, changinging from int64 to str

def int_to_string(num):
    "int to str"
    return str(num)

def get_list(subset, label):
    "get list"
    string_list = []
    for x in subset[label]:
        x= int_to_string(x)
        string_list.append(x)
    return string_list

string_geoid = get_list(d2_subset,'geoid')
string_geoid   #string list of geoid

# replace this list with column in Census
data2_c['geoid'] = string_geoid

data2_c.dtypes  # checks that type for geoid is a string(aka object)

geoid               object
cr_geoid             int64
name                object
original_id          int64
pop100               int64
hu100                int64
state_place_fips     int64
dtype: object

In [8]:
#Process geoid colum in census dataset, for each string do an approprioate slicing (5:11)

def calculate_tract(df):
    # Assuming the column name is 'column_name' and the DataFrame is 'df'
    new_list = []
    for x in df:
        sliced_string = x[5:11]  # Change the slice range as per your requirement
        new_list.append(sliced_string)
    return new_list


calc_t= calculate_tract(string_geoid)

#  add calculatedtract column to oG data set for census  # works 
data2_c['Calculated_Tract'] = calc_t
data2_c.head()    # type for calculated tract is object

,geoid,cr_geoid,name,original_id,pop100,hu100,state_place_fips,Calculated_Tract
0,250250703001010,178,Bay Village,33,49,5,2507000,070300
1,250250703001011,178,Bay Village,33,201,143,2507000,070300
2,250250703001012,178,Bay Village,33,324,235,2507000,070300
3,250250703001013,178,Bay Village,33,0,0,2507000,070300
4,250250703001014,178,Bay Village,33,5,5,2507000,070300

In [9]:
data2_c.dtypes

geoid               object
cr_geoid             int64
name                object
original_id          int64
pop100               int64
hu100                int64
state_place_fips     int64
Calculated_Tract    object
dtype: object

In [13]:
# Convert the 'Calculated_Tract' column to numeric, handling errors
data2_c['Calculated_Tract'] = pd.to_numeric(data2_c['Calculated_Tract'], errors='coerce')

In [10]:
data1_b.columns

Index(['Unnamed: 0', 'hl1_x', 'body', 'llama_prediction', 'Explicit_Pass_1',
       'NER_Pass_1', 'NER_Pass_1_Sorted', 'NER_Pass_1_Coordinates',
       'NER_prediction', 'NER_Sorted', 'NER_Sorted_Coordinates', 'Tracts',
       'position_section', 'position_subsection', 'hl1_y', 'hl2', 'author',
       'lede', 'pub_date', 'indexing_terms', 'year', 'actual_body_word_count',
       'body_cleaned', 'longitude', 'latitude', 'tract_2010'],
      dtype='object')

In [14]:

new_census_subset =  data2_c[['Calculated_Tract', 'name']]

# this new dataset wil be merged with other census on Tract and Calculated Tract





merged_data = data1_b.merge(new_census_subset[['Calculated_Tract','name']] , left_on='tract_2010', right_on= "Calculated_Tract", how='inner')


merged_data